In [2]:
import numpy as np


## how to create an array

In [3]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a)
print(b)


[1 2 3 4 5]
[5 6 7 8 9]


In [4]:
type(a)

numpy.ndarray

## basic operations of array

In [5]:
print(a+b)
print(a-b)
print(a*b)

[ 6  8 10 12 14]
[-4 -4 -4 -4 -4]
[ 5 12 21 32 45]


In [6]:
## creating 2d array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [7]:
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
print(a2.shape)
print(a3.shape) #2 2d array with 2 rows and 3 columns

(2, 3)
(2, 2, 3)


In [9]:
print(a2.ndim)#ndim num of dimension
print(a3.ndim)

2
3


In [10]:
#creating a 4d array
a4 = np.array([[[[1,2],[3,4]],
                [[5,6],[7,8]]]
                ,[[[9,10],[11,12]]
                  ,[[13,14],[15,16]]]])
print(a4)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


In [11]:
print(a2.dtype) #64 system ke according

int64


In [12]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(0,21,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
np.random.randint(1,11, size=(3,3))

array([[2, 6, 6],
       [9, 7, 7],
       [4, 6, 6]], dtype=int32)

In [18]:
x=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
y=np.array([[9,8,7],
            [6,5,4],
            [3,2,1]])
print(x)
print(y)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [19]:
print(x+y)
print(x-y)
print(x*y)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [20]:
print(x@y)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [21]:
x.prod()#product of element in the array

np.int64(362880)

In [22]:
x.mean()

np.float64(5.0)

In [24]:
y.mean()

np.float64(5.0)

In [25]:
x.mean(axis=0)

array([4., 5., 6.])

In [27]:
y.mean(axis=1) #mean of each row

array([8., 5., 2.])

In [28]:
print(x.sum()) #sum of element in the array
print(x.var()) #varieance of all element in the array
print(x.std()) #standard deviation of all element in the array

45
6.666666666666667
2.581988897471611


In [30]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25)) #25th percentile
print(np.percentile(a,50)) #50th percentile
print(np.percentile(a,75)) #75th percentile

3.0
5.0
7.0


In [34]:
b=np.array([[90,89,88,87],
            [86,85,84,83],
            [78,77,76,75],
            [66,35,47,78]])
print(b)

[[90 89 88 87]
 [86 85 84 83]
 [78 77 76 75]
 [66 35 47 78]]


In [35]:
print('8*2')
print(b.reshape(8*2))

8*2
[90 89 88 87 86 85 84 83 78 77 76 75 66 35 47 78]


In [36]:
print('2*8')
print(b.reshape(2*8))

2*8
[90 89 88 87 86 85 84 83 78 77 76 75 66 35 47 78]


In [37]:
print(b)

[[90 89 88 87]
 [86 85 84 83]
 [78 77 76 75]
 [66 35 47 78]]


In [38]:
print(b[0])
print(b[1])

[90 89 88 87]
[86 85 84 83]


In [39]:
print(b[0,0])

90


In [40]:
print(b[:3])
print(b[3:])

[[90 89 88 87]
 [86 85 84 83]
 [78 77 76 75]]
[[66 35 47 78]]
